#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     unused,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     unused,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/* Change log
16 9 2013 Jonathan - Program created
17 9 2012 Jonathan - *Added seperate tasks for left and right drive control
										 *Added basic drive controls - left stick = left motor & right stick = right motor
										 *Note - controllers have inverted y values
*/
task driveL() {
	while(true) {
		if(joy1_y1 < -25) {
			motor[left] = 100;
		}
		if(joy1_y1 > 25) {
			motor[left] = -100;
		}
	}
}

task driveR() {
	while(true) {
		if(joy1_y2 < -25) {
			motor[right] = 100;
		}
		if(joy1_y2 > 25) {
			motor[right] = -100;
		}
	}
}

task main() {
	waitForStart();
	StartTask (driveL);
	wait1Msec(5);
	StartTask (driveR);
	wait1Msec(5);
}
