#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     unused,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     unused,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/* Change log
16 9 2013 Jonathan - Program created
*/
task drive() {

}

task main() {
	waitForStart();
	StartTask (drive);
	wait1Msec(5);
}
