#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     conveyorL,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     conveyorR,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     lifter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     flag,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftB,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftF,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    chuterelease,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/*
21 09 2013 Jonathan - *code created
										  *code compressed into single task
										  *added a convyor belt task
										  *commented out 85 limit until further notice
										  *added second conveyor belt motor
										  *commented out conveyor belt task
23 09 2013 Jonathan - *bug fixing
03 10 2013 Jonathan - *changed motor config for new robot
*/
int position = 0;

task drive() {
	while(true){

		//Get joystick values
		getJoystickSettings(joystick);

		//Define variables
		short y1 = -joystick.joy1_y1;
		short y2 = -joystick.joy1_y2;

		//If statement determines motor movement
		if ((y2 > -15 && y2 < 15) && (y1 > -15 && y1 < 15)) {
   		motor[rightB] = 0;
   		motor[rightF] = 0;
   		motor[leftB] = 0;
			motor[leftF] = 0;
 		}

		else {
			motor[rightB] = (y2 * .5);
			motor[rightF] = (y2 * .5);
			motor[leftB] = (y1 * .5);
			motor[leftF] = (y1 * .5);
 		}


	//	}

		/*
		//Left wheel threshold
		else if(y1 >= 85) {
			motor[leftF] = 85;
			motor[leftB] = 85;
		}

		//Right wheel threshold
		else if(y2 <= -85) {
			motor[rightF] = -85;
			motor[rightB] = -85;
		}
		*/
		//Motors not moving
/*		else {
			motor[leftF] = 0;
			motor[leftB] = 0;
			motor[rightF] = 0;
			motor[rightB] = 0;
		}
*/
		//Wait to avoid latency issues
		wait1Msec(5);
	}
}



//Conveyor belt
task convey() {
	while(true) {

		//Get joystick values
		getJoystickSettings(joystick);

		//If A is pressed, conveyor moves
		if(joy2Btn(01) == 1) {
			motor[conveyorR] = 50;
			motor[conveyorL] = 50;
		}
		else{
			motor[conveyorR] = 0;
			motor[conveyorL] = 0;
		}

		//Wait to avoid latency issues
		wait1Msec(5);
	}
}


//chuteServo task
task chuteServo() {
	while(true) {

	//Get joystick values
	getJoystickSettings(joystick);

	//if B is pressed, servo moves
	if(joy2Btn(03) == 1) {
		servo[chuterelease] = 130;
		wait1Msec(500); //wait time
		position = 1; //position is set to 1 once the servo is open
		//wait1Msec(2000);
	}
	if (joy2Btn(02) == 1) {
		servo[chuterelease] = 0;
		wait1Msec(500); //wait time
		position = 0; //position is set to 0 once the servo is closed
		//wait1Msec(2000);
		}
		wait10Msec(5);
	}
}

task lift() {
	while(true){
		getJoystickSettings(joystick);
		//if LB is pressed, lift goes up
		if(joy2Btn(05) == 1){
			motor[lifter] = 60;
		}
		//if RB is pressed, the lift goes down
		else if(joy2Btn(06) == 1){
			motor[lifter] = -60;
		}
		else{
			motor[lifter] = 0;
		}
		wait1Msec(5);
	}
}

//move flag task.
task flaglift() {
	while(true){
		getJoystickSettings(joystick);

		if(joy1Btn(06) == 1){
			motor[flag] = 75;
		}

		else{
			motor[flag] = 0;
		}
		wait1Msec(5);
	}
}


//Main task
task main()
{
	waitForStart();
	StartTask(drive);
	StartTask(convey);
	StartTask(chuteServo);
	StartTask(lift);
	StartTask(flaglift);
	while(true){}
}
