#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     unused,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     unused,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/* Change log
16 9 2013 Jonathan - *Program created
17 9 2013 Jonathan - *Added seperate tasks for left and right drive control
										 *Added basic drive controls - left stick = left motor & right stick = right motor
										 *Note - controllers have inverted y values
18 9 2013 Jonathan - *Drive control fixed
										 *Basic scaling attempted
*/

//Left tread drive control
task driveL() {
	while(true) {

		getJoystickSettings(joystick);

		//Define y1 variable
		int y1 = -joystick.joy1_y1;

		//Left tread forward
		if(y1 > 25) {
			motor[left] = y1;
		}

		//Left tread backward
		else if(y1 < -25) {
			motor[left] = -y1;
		}

		//Motor unused
		else {
			motor[left] = 0;
		}
		wait1Msec(5);
	}
}



//Right tread drive control
task driveR() {
	while(true) {

		getJoystickSettings(joystick);

		//Define y2 variable
		int y2 = -joystick.joy1_y2;

		//Right tread forward
		if(y2 > 25) {
			motor[right] = y2;
		}

		//Right tread backward
		else if (y2 < -25) {
			motor[right] = -y2;
		}

		//Motor unused
		else {
			motor[right]=0;
		}
		wait1Msec(5);
	}
}


//MAIN TASK (YEAH)
task main() {
	waitForStart();
	StartTask (driveL);
	StartTask (driveR);
	while(true){}

}
