#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftF,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftB,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rightF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     rightB,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task drive()
{
	while(true)
	{
		if(joy1_y1 > 50)
		{
			motor[leftF] = 100;
			motor[leftB] = 100;
		}
	}
}

task main()
{
	StartTask (drive);
}
