#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTMC,           sensorI2CHiTechnicCompass)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	//define variables
	short startPos;
	short endPos;
	short current;

void turn(float deg){


	startPos = 	SensorValue[HTMC];
	endPos = startPos + deg;
 if(deg>0){
   	endPos = startPos + deg;
	if(endPos>359){
		endPos = endPos - 360;
	}

	current = SensorValue[HTMC];
	if (current>endPos){

	while(current > endPos){
		current = SensorValue[HTMC];
		motor[motorFL] = 25;
		motor[motorBL] = 25;
		motor[motorFR] = -25;
		motor[motorBR] = -25;
	}
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;

}

if (current<endPos){

	while(current < endPos){
		current = SensorValue[HTMC];
		motor[motorFL] = 25;
		motor[motorBL] = 25;
		motor[motorFR] = -25;
		motor[motorBR] = -25;
	}
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;

}
}
 if(deg<0){
   	endPos = startPos + deg;
	if(endPos<0){
		endPos = endPos + 360;
	}

	current = SensorValue[HTMC];
	if (current<endPos){

	while(current < endPos){
		current = SensorValue[HTMC];
		motor[motorFL] = -25;
		motor[motorBL] = -25;
		motor[motorFR] = 25;
		motor[motorBR] = 25;
	}
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;

}

if (current>endPos){

	while(current > endPos){
		current = SensorValue[HTMC];
		motor[motorFL] = -25;
		motor[motorBL] = -25;
		motor[motorFR] = 25;
		motor[motorBR] = 25;
	}
		motor[motorFL] = 0;
		motor[motorBL] = 0;
		motor[motorFR] = 0;
		motor[motorBR] = 0;

}
}
}

task main(){

	wait10Msec(5);

	turn(-100);



}
